name: Documents Search CI

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: search-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Install pnpm
        uses: pnpm/action-setup@v6.0.9

      - name: Use Node
        uses: actions/setup-node@v7.0.0
        with:
          node-version: 24

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate content
        run: pnpm run generate-content-json

      - name: Upload search data artifact
        uses: actions/upload-artifact@v7.0.1
        if: success()
        with:
          name: search-data
          path: public/search-data/
          retention-days: 30
